---
title: "DESeq2 with phyloseq"
author: "J. Ignacio Lucas Lledó"
date: "16/3/2020"
output: html_document
bibliography: deseq2.bib
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(phyloseq)
library(DESeq2)
library(ggplot2)
load('../2020-02-27/ps.RData')
```

```{r deseq2}
# I had set isoline as 'ordered' just to have isoline 6 in first position in plots.
# Now, I should *disorder* it.
sample_data(ps)$isoline <- factor(sample_data(ps)$isoline, ordered=FALSE)
ds <- phyloseq_to_deseq2(ps, ~ seqrun + isoline + age)
ds <- DESeq(ds, test='Wald', fitType='parametric')
res <- results(ds, cooksCutoff = FALSE)
sigtab <- res[which(res$padj < 0.01), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(ps)[rownames(sigtab), ], "matrix"))
dim(sigtab)
```
```{r plot}
theme_set(theme_bw())
scale_fill_discrete <- function(palname = "Set1", ...) {
    scale_fill_brewer(palette = palname, ...)
}
# Phylum order
x = tapply(sigtab$log2FoldChange, sigtab$Phylum, function(x) max(x))
x = sort(x, TRUE)
sigtab$Phylum = factor(as.character(sigtab$Phylum), levels=names(x))
# Genus order
x = tapply(sigtab$log2FoldChange, sigtab$Genus, function(x) max(x))
x = sort(x, TRUE)
sigtab$Genus = factor(as.character(sigtab$Genus), levels=names(x))
ggplot(sigtab, aes(x=Genus, y=log2FoldChange, color=Phylum)) + geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))

```

```{r sessioninfo}
save(ds, res, sigtab, file='DESeq2.RData')
sessionInfo()
```

# References